#!/usr/bin/env bash

IFS='+' read -ra ARGS <<< "$QUERY_STRING"

TITLE=$(echo "${ARGS[@]}" | tr '[:lower:]' '[:upper:]')

START=$(date +%s%N)

echo 'Content-Type: text/html'
echo ''
../target/release/tortordle --color --columns=12 --words "${ARGS[@]}" | aha --black --title "$TITLE" -s

ELAPSED=$((($(date +%s%N) - $START)/1000000))
echo -e "$(date -Iseconds)\t${REMOTE_ADDR}\t${ELAPSED}ms\t${QUERY_STRING}" >> analyses.log
