#!/usr/bin/env bash

IFS='+' read -ra ARGS <<< "$QUERY_STRING"

TITLE=$(echo "${ARGS[@]}" | tr '[:lower:]' '[:upper:]')

START=$(date +%s%N)

ENCRYPTED=$(echo "$QUERY_STRING" | openssl enc -e -des3 -base64 -A -pass pass:tortordle -pbkdf2)

echo "Content-Type: text/html

<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset='utf-8'>
    <title>Tortordle: $TITLE</title>
    <link rel='stylesheet' href='../style.css'>
    <script>
    function copyToClipboard(text) {
        // This is terrible.
        var dummy = document.createElement('input');
        dummy.setAttribute('value', text);
        document.body.appendChild(dummy);
        dummy.select();
        document.execCommand('copy');
        document.body.removeChild(dummy);
    }
    function copyLink() {
        copyToClipboard(document.location.href);
    }
    function copySpoilerFreeLink() {
        const url = new URL('./no-spoiler?$ENCRYPTED', document.baseURI).href;
        copyToClipboard(url);
    }
    </script>
</head>
<body>
    <pre>"

../target/release/tortordle --color --columns=12 --words "${ARGS[@]}" \
| aha --no-header --black

echo "

                        <button onclick='copyLink()'>Copy Link</button> <button onclick='copySpoilerFreeLink()'>Copy Spoiler-Free Link</button>

                        &lt;&lt; <a href='..'>Analyse Another Game</a>
    </pre>
</body>
</html>"

ELAPSED=$((($(date +%s%N) - $START)/1000000))
echo -e "$(date -Iseconds)\t${REMOTE_ADDR}\t${ELAPSED}ms\t${QUERY_STRING}" >> analyses.log
