#!/usr/bin/env bash

DECRYPTED=$(echo "$QUERY_STRING" | openssl enc -d -des3 -base64 -pass pass:tortordle -pbkdf2)

echo "Content-Type: text/html

<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='refresh' content='1; url=./analysis?$DECRYPTED'>
    <link rel='stylesheet' href='../style.css'>
    <title>Tortordle: Wordle Game Results</title>
</head>
<body class='larger'>
<a href='./analysis?$DECRYPTED' style='color:white'>Redirecting...</a>
</body>
</html>"
